s3_bucket                = "terraform-statefiles-bucket-163450518166"
region                   = "us-east-1"
glue_job_name            = "TestDeployScript"
glue_job_test_script_loc = "glue/scripts/TestDeployScript.py"
glue_job_name_1            = "NewTestDeployScript"
glue_job_test_script_loc_1 = "glue/scripts/NewTestDeployScript.py"
